const peças = ['parafuso', 'rosca', 'botão', 'interruptor']

console.log('quantidade de caracteres')
if (peças.length <10){console.log('a peça pode ser cadastrada')}

console.log('quantidae de caracteres')

for (let index =0; index < peças.length ++){const ayual = peças [index];}
if (atual.length <3){console.log(atual + ':peça possui nome inferior a 3 caracteres não pode ser cadastrada')}
else console.log(atual + ':peça pode ser cadastrada')
